### ISSUE TITLE
[Feature Request] Loading modal

### ISSUE THREAD

**Issue by russellhoff** [tehapo/WizardsForVaadin#17]
Sometimes, the transition of stepping forward is not instantaneous. For instance, in my application when the user presses first step's "next" button I fetch some data over a database. Depending on the amount of data, this operation may last from 2 seconds to 10 -and we all know how desperate users are- until the Step 2 is shown.

It would be great if a modal is shown just after pressing the next button and until the next step is shown.

The thing is that glueing up steps is a bit complicated, as each step is built solely and added at the same time. How hard would this new feature to include in it?

Thanks for reading me.

**Comment by tehapo** [comment]
I'm not 100% sure I understood the problem here, but I think this kind of a feature should not be part of the Wizards add-on. Instead you could construct your wizard step in such a way that it is displayed immediately and it would show a loading spinner until the database query has returned the results.

Notice that in Vaadin you need to either use server [push](https://vaadin.com/docs/-/part/framework/advanced/advanced-push.html) or do some [polling](https://vaadin.com/wiki/-/wiki/Main/Using+polling) in order to apply UI changes from a background thread.

Feel free to reopen this ticket if I misunderstood something.
